---
language: node_js

node_js:
  - "12"

cache: yarn

script:
  - yarn lint
  - yarn test
  - yarn build
  # replace the pathways service in the config file with the gh static location
  # and the cql-to-elm service with a public one
  # -i means in-place
  # see https://stackoverflow.com/a/11245501
  # note multiline string here gets converted into one line, not 3
  - >
      sed -i "/pathwaysService:/c\  pathwaysService: 'https://mcode.github.io/pathways/static/pathways/'," build/config.js
      &&
      sed -i "/cqlToElmWebserviceUrl:/c\  cqlToElmWebserviceUrl: 'https://cql-translation-service-zfk47ib3kq-uc.a.run.app/cql/translator'," build/config.js

deploy:
  provider: pages
  local_dir: build
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
